krux/python-krux-stdlib

krux/io.py

Exposes the `shell` parameter to Popen. If `shell` is not specified and `command` is a string, set `shell=True` so the shell will parse the command instead of splitting it on whitespace.

OPS-2630 Make IORunCmd more robust

---

.travis.yml
krux/logging.py
setup.py

before trying to log to it; some linux hosts, such as CI docker instances, tend to not have it.

check for log device

---

tests/unit_tests/test_cli.py

Fixing the unit tests that were failing due to incorrect mocking of `sys.exit()`.

Fixing the sys.exit() unit tests

---

krux/cli.py
tests/unit_tests/test_cli.py

Unit tests for `raise_critical_error()` and `context()`. Also improved `raise_critical_error()` so that it will show the complete traceback.

Phan raise critical error

---

krux/cli.py
setup.py

This change allows inheriting classes (eg krux_monitoring_scripts.cli) to fully choose a default behavior regarding logging...
Mainly, if the inheriting class chooses to suppress stdout logging by default, those scripts will still get a --log-to-stdout command line arg to re-enable it.
If the inheriting class doesn't explicitly disable stdout logging, all behavior (including the --no-log-to-stdout arg) remains the same.

Better handling of stdout/stderr log supression

---

krux/io.py
requirements.pip
setup.py
tests/unit_tests/test_io.py

Instead of built-in subprocess module of Python 2.6, use the back ported version from python 3.3. Expose the timeout functionality of the new version.
Version incremented

Subprocess library update

---

krux/io.py
setup.py
tests/unit_tests/test_io.py

Three updates to the timeout feature that was introduced in v.2.1.3:
1. There is an optional parameter that can be used to send anything other than `SIGTERM` to terminate the process upon timeout
1. The unit test for timeout is improved, mainly to make sure the signals is sent to the process upon timeout.
1. 'exec ' prefix is added to the command when `shell` and `timeout` parameters are used together to avoid confusion.

IO subprocess timeout

---

krux/cli.py
setup.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_logging.py

1. Created `--no-syslog-facility` to disable syslog logging.
1. Modified `setup()` method of `krux.cli` unit test
1. Created unit tests for `--syslog-facility` and `--no-syslog-facility` CLI arguments
1. Created basic unit tests for `krux.logging`

Phan logger syslog

---

krux/logging.py
setup.py
tests/unit_tests/test_logging.py

When `--no-log-to-stdout` is used, nothing should be printed out to the terminal. We used to do that by not setting the log level. However, `krux-boto` sets the log level on its own to minimize the debugging logs from the boto itself. This accidentally overrides `--no-log-to-stdout` CLI argument.
To mitigate that, when `--no-log-to-stdout` is set, explicitly disable log propagation. This will stop the logs to hit the ancestor loggers, stopping them from being printed on the terminal. Any log handler attached to the application logger will still log as expected.
Refer to [StackOverflow question](http://stackoverflow.com/questions/21234772/python-tornado-disable-logging-to-stderr) on this.

Disabling propagation when not logging to stdout

---

krux/util.py

This PR changes the name of a variable so that the same name is not used twice. Re-using the name causes unnecessary confusion.
* `krux.util.flatten()`
The change was tested via the unit test

Changing the variable name to avoid shadowing

---

krux/object.py
tests/unit_tests/test_object.py

This PR creates an abstract class to simplify the common Krux coding pattern.
Because those three lines are repeated in pretty much all Krux libraries.
`krux/object.py`
The change was manually tested on the development environment and through the unit test.
our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review)

krux.object.Object

---

krux/io.py
setup.py
tests/unit_tests/test_io.py

Detect shell escapes in commands called via `krux.io`.

don't allow shell=True in subprocess.Popen() calls

---

README.md
krux/__init__.py
krux/cli.py
setup.py
tests/unit_tests/test_cli.py

This PR provides a way to add `--version` CLI argument to all `krux.cli.Application`-inherited classes.
Having `--version` is a nice way to quickly check the version of the CLI application without checking the source or the package manager.
The changes were tested manually in the development environment and via unit tests.
our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review)

Adding --version to krux.cli.Application

---

krux/__init__.py
requirements.pip

This PR increments the version of `kruxstatsd` to the latest.
Version 0.3.0 of `kruxstatsd` had an error in `install_requires` parameter of `setup.py` that causes version collisions. Version 0.3.1 fixes it.
The change was tested manually in `ci-a-trusty-worker003.krxd.net` and via nosetests.
our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review)

PE-2585: Incrementing version of kruxstatsd

---

krux/__init__.py

This PR is simply incrementing the patch version to release the python warning bug fixed in #48.
We want to release the fix on python warning as a new version.
The change was tested by running `python setup.py develop` in the development environment.
`krux/__init__.py`

Incrementing the patch version to fix the bug with python warnings

---

example.py
krux/__init__.py
krux/cli.py
tests/unit_tests/test_cli.py

**#### CHANGE PROPOSAL ####**
When instantiating a `krux.cli.Application`-based class, allow the user to provide their own arguments, overriding the process’ command-line arguments.
This adds a new parameter to `krux.cli.Application.init()`: `parser_args`.
To run unit tests and experiments on `krux.cli.Application`-based apps, it would helpful if we could override the command-line arguments that the app would normally get from `sys.argv`. This is functionality that `argparse.ArgumentParser` already supports, and since KruxParser is based on it, this requires changes to just two lines of code in `krux/cli.py`.
Since `cli.Application` relies heavily on command-line arguments, and since it consumes & processes those arguments on initialization, these arguments must be passed in to …

Allow override of cli.Application argv arguments on instantiation

---

krux/__init__.py
krux/cli.py
krux/parser.py
krux/wrapper.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_object.py
tests/unit_tests/test_parser.py
tests/unit_tests/test_wrapper.py

The PR creates an environment variable fall back for CLI arguments. This would allow the arguments to be set via environment variables. The precedence is `--foo` > `ENV_FOO` > default value.
1. This makes things easy when we need to change the default value of an argument.
2. This makes things easy when there are lots of arguments.
3. This makes things easy when there is an argument with a long value.
This PR create two classes `KruxParser` and `KruxGroup` that inherit `argparse.ArgumentParser` and `argparse._ArgumentGroup`, respectively. `KruxParser` is only there to create a `KruxGroup` object instead of `argparse._ArgumentGroup` object. `KruxGroup` object hijacks the arguments and override the `default` parameter with the value from environment variables. It also augment the help text …

PE-4210: Create an environment variable fall back for CLI arguments

---

krux/__init__.py
krux/parser.py
tests/unit_tests/test_parser.py

This PR fixes a bug where `KruxParser.add_argument_group()` throws an error when positional arguments are used. This was found when `parser.add_subparsers()` method was used because `argparse` internally calls `parser.add_argument_group(title, description)`.
This is a bug fix.
A unit test to cover this case is written. The test correctly failed before the fix with the same symptom. The test passed after the fix.
been appropriately socialized to avoid surprises.

Bugfix for KruxParser.add_argument_group()

---

krux/__init__.py
krux/stats.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_stats.py

Changes the default behaviour of the stats client to no longer include the host and environment names. Projects including this code can request the `legacy` mode and get the old behaviour if desired.
Krux is moving away from graphite and towards a service. That service aggregates stats by tags, and does not permit the use wildcards in stat names in the UI.
This means that the stats we send currently have to be run through a rewrite proxy, to remove the host and environment names. This change makes that no longer necessary, and permits us to (eventually!) remove the rewriting proxy on each host.
Fixed a test that only worked when run via `nosetests`, which has been deprecated, and which IDEs no longer commonly use.
This is a WIP, so testing so far has been light.
* unit tests have been …

stats compatibility

---

krux/__init__.py
setup.py

Setting `python_requires='<4'` in `setup.py` will effectively support any version of `2.7.*` and any version of 3. Technically, it claims to support versions less than 2.7, but at this point we don’t care.

Fix python_requires

---

Pipfile
Pipfile.lock
krux/__init__.py
krux/cli.py

When [`cli.Application`](https://github.com/krux/python-krux-stdlib/blob/0f11a25fdf267c3d577aae2f881eefbcac4a3b89/krux/cli.py#L81) is called with [`lockfile = False`](https://github.com/krux/python-krux-stdlib/blob/0f11a25fdf267c3d577aae2f881eefbcac4a3b89/krux/cli.py#L95), it properly does not attempt to acquire a lock, but it still includes the `--lock-dir` flag, because [`get_parser`](https://github.com/krux/python-krux-stdlib/blob/0f11a25fdf267c3d577aae2f881eefbcac4a3b89/krux/parser.py#L30) is not being passed [`lockfile`](https://github.com/krux/python-krux-stdlib/blob/0f11a25fdf267c3d577aae2f881eefbcac4a3b89/krux/cli.py#L122).
I updated the `Pipfile` to not require a specific python version, then created a virtualenv for `2.7.14`, and `3.6.9`, then ran `nosetests`. Everything was a …

Pass lockfile to get_parser

---

krux/__init__.py
setup.cfg
setup.py
tests/unit_tests/test_cli.py
tests/unit_tests/test_io.py
tests/unit_tests/test_logging.py
tests/unit_tests/test_object.py
tests/unit_tests/test_stats.py
tests/unit_tests/test_util.py
tests/unit_tests/test_wrapper.py

This PR updates the library so it can be tested in our CI using `pytest`.
We do not want to use the old `nosetests` anymore.
```bash
$ python -m setup citest
running pytest
running egg_info
writing krux_stdlib.egg-info/PKG-INFO
writing dependency_links to krux_stdlib.egg-info/dependency_links.txt
writing requirements to krux_stdlib.egg-info/requires.txt
writing top-level names to krux_stdlib.egg-info/top_level.txt
reading manifest file 'krux_stdlib.egg-info/SOURCES.txt'
writing manifest file 'krux_stdlib.egg-info/SOURCES.txt'
running build_ext
=============================================================================== test session starts ================================================================================
platform darwin -- Python 3.7.4, pytest-5.2.1, py-1.8.0, …
```

W-6690988: Migrate over to pytest

---

Pipfile
krux/__init__.py

Upgrades the version of pystache used for testing to ~=0.6.0.
Breaking builds.
Self-evident.
As-yet untested. My laptop’s Python env. is totally borked right now, so I’m using CloudBees to test for me.
our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review).
are up to date without going over a major version.
been appropriately socialized to avoid surprises.

upgrade pystache to 0.6.0
